### ISSUE TITLE
Améliorer le fichier HTML de ma page web 

### ISSUE THREAD

**Issue by Arij-28** [Arij-28/monprojet2#13]

**Comment by StephaneSALVADOR** [comment]
Très bien, j'y travail.

**Comment by StephaneSALVADOR** [comment]
Modifications poussées sur la branche "NewBranch_monprojet2".

**Comment by Arij-28** [comment]
Reçu

**Comment by StephaneSALVADOR** [comment]
![push_GitHub](https://github.com/Arij-28/monprojet2/assets/150392461/da907a63-6d75-4d09-971c-2921113aed67)
